version: "3.8"

services:
  chain:
    image: "${SERVICE}_${NETWORK}_${VERSION}"
    container_name: "${SERVICE}_${NETWORK}_${SERVER_TYPE}_${VERSION}"
    ports:
      - $P2P_PORT:$P2P_PORT
    env_file:
      - env
    volumes:
      - $HOME/.${SERVICE}:/root/.${SERVICE}
      # - $HOME/validators/config/_app.toml:/root/.${SERVICE}/config/app.toml
      # - $HOME/validators/config/_client.toml:/root/.${SERVICE}/config/client.toml
      # - $HOME/validators/config/_config.toml:/root/.${SERVICE}/config/config.toml
    networks:
      - net
    deploy:
      resources:
        reservations:
          # cpus: "2"
          memory: "8G"

networks:
  net:
    driver: bridge
