version: "3.8"

services:
  chain:
    image: "${SERVICE}_${NETWORK}"
    container_name: "${SERVICE}_${NETWORK}_${SERVER_TYPE}"
    env_file:
      - env
    volumes:
      - $HOME/.${SERVICE}:/root/.${SERVICE}
    networks:
      - net

networks:
  net:
    driver: bridge
