version: "3.8"

services:
  chain:
    image: "${SERVICE}_${NETWORK}_${VERSION}"
    container_name: "${SERVICE}_${NETWORK}_${SERVER_TYPE}_${VERSION}"
    ports:
      - $P2P_PORT:26656
      - $PROMETHEUS_PORT:26660
      ## CONDITIONAL_PORTS ##
    env_file:
      - env
    volumes:
      - $HOME/.${SERVICE}:/root/.${SERVICE}
    networks:
      - net
    # deploy:
    #   resources:
    #     reservations:
    #       # cpus: "2" # seems to be working only in swarm
    #       memory: "8G"

networks:
  net:
    driver: bridge
